version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=BancoDeConhecimentoInteligentedb;Username=postgres;Password=your_secure_password
    networks:
      - BancoDeConhecimentoInteligente-network

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password
      - POSTGRES_DB=BancoDeConhecimentoInteligentedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - BancoDeConhecimentoInteligente-network

networks:
  BancoDeConhecimentoInteligente-network:
    driver: bridge

volumes:
  postgres_data: